language: csharp
mono: none
os: windows
dotnet: 2.1.502
cache:
  directories:
    - node_modules
    - app/node_modules
    - $HOME/.cache/electron
    - $HOME/.cache/electron-builder
    - $HOME/.npm/_prebuilds
env:
  global:
    - ELECTRON_CACHE=$HOME/.cache/electron
    - ELECTRON_BUILDER_CACHE=$HOME/.cache/electron-builder
before_script:
  - chmod +x ./buildServerApp.sh
  - export PATH="$PATH:/home/travis/.dotnet/tools"
  - npm install electron-packager --global
script:
  - ./buildServerApp.sh